dateModified: 1741547420
email:
  fromEmail: sergiopgomes92@gmail.com
  fromName: Motoventure
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    4a97ac01-d623-47fa-a056-df66c6a29e05: Motoventure # Motoventure
    06de1850-ebc9-4063-8123-ad323d6b5f99: 'Public Schema' # Public Schema
    64defcb6-61e8-40f3-ab39-c26d22f13b81: Motoventure # Motoventure
    008678e4-5b06-4bbc-a5e2-eafa81b99cff: Home # Home
    edc4eadb-2ba5-48db-8e0a-c80804a8477c: Home # Home
system:
  edition: solo
  live: true
  name: Motoventure
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
