defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 008678e4-5b06-4bbc-a5e2-eafa81b99cff # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4a97ac01-d623-47fa-a056-df66c6a29e05: # Motoventure
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
